namespace: school-ns

#app deployment

#deployment details
replicas: 2
deployment:
  name: school-app-deployment
  labels:
    app: school-app
  port:  80
  image:
    repository: bhagwat07/school-app
    tag: v1.0.0

#service details

service:
  app: school-app
  type: LoadBalancer
  port: 80